import { Toaster } from 'components/ui/toaster';
import './globals.css';

export const metadata = {
  title: 'Welcome to org',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="flex justify-center">
      <body className="w-[95%] pt-3">
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
